name: _test-a

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run _test-b.yml --repo "${GITHUB_REPOSITORY}"
